apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-java-payload
  labels:
    app: secure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-java
  template:
    metadata:
      labels:
        app: hello-java
    spec:
      containers:
      - name: java-app
        image: ghcr.io/mithun-08/hello-java@sha256:57f468c59c7bc7e814ab325f87ea8141e2dc6027981f773c0e4832c9f57d6a87
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: ghcr-secret
